service: hello

# useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x

functions: 
  # hello:
  #   handler: src/hello.handler
  #   events:
  #     - httpApi: GET /hello

  listCategories:
    handler: src/functions/category/listCategories/handler.listCategories
    events:
      - httpApi: GET /listCategories
  createCategory:
    handler: src/functions/category/createCategory/handler.createCategory
    events:
      - httpApi: POST /createCategory

  deleteCategory: 
    handler: src/functions/category/deleteCategory/handler.deleteCategory
    events:
      - httpApi: DELETE /deleteCategory   

  updateCategory: 
    handler: src/functions/category/updateCategory/handler.updateCategory
    events:
      - httpApi: PUT /updateCategory
  createProduct:
    handler: src/functions/product/createProduct/handler.createProduct
    events:
      - httpApi: POST /createProduct
  listProducts:
    handler: src/functions/product/listProducts/handler.listProducts
    events:
      - httpApi: GET /listProducts
  deleteProduct:
    handler: src/functions/product/deleteProduct/handler.deleteProduct
    events:
      - httpApi: DELETE /deleteProduct
  updateProduct:
    handler: src/functions/product/updateProduct/handler.updateProduct
    events:
      - httpApi: PUT /updateProduct
 

plugins:
  - serverless-esbuild
  - serverless-offline

custom: 
  esbuild: 
    bundle: true
    minify: true

resources:
  Resources:
    Category:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: Category
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH    
    Product:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: Product
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH   
    
